name: Clean up

on:
  check_run:
    types: completed

jobs:
  Post:
    runs-on: ubuntu-latest
    name: Report result
    if: ${{ github.check_run.pull_requests }}

    steps:
      - uses: actions/checkout@v3
      - name: Clean up
        run: |
          pip install jwt requests
          python ci_tools/bot_clean_up.py
        shell: bash
        env:
          PEM: ${{ secrets.BOT_PEM }}
