name: Pyccel CUDA tests

on:
  pull_request:
    branches: [ cuda_main, cuda_main_temp ]

jobs:
  Linux:

    runs-on: ubuntu-latest
    container: nvidia/cuda:11.7.1-devel-ubuntu20.04
    steps:
      - uses: actions/checkout@v2
      - name: CUDA Version
        run: nvcc --version # cuda install check
      - name: Install dependencies
        uses: ./.github/actions/linux_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Fortran/C tests with pytest
        uses: ./.github/actions/pytest_run
      - name: Ccuda tests with pytest
        uses: ./.github/actions/pytest_run_cuda
      - name: Python tests with pytest
        uses: ./.github/actions/pytest_run_python
      - name: Parallel tests with pytest
        uses: ./.github/actions/pytest_parallel

  # Windows:

  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup Python 3.9
  #       uses: actions/setup-python@v3
  #       with:
  #           # The second most recent version is used as
  #           # setup-python installs the most recent patch
  #           # which leads to linking problems as there are
  #           # 2 versions of python3X.a and the wrong one
  #           # is chosen
  #           python-version: 3.9
  #     # Uncomment to examine DLL requirements with 'objdump -x FILE'
  #     #- name: Install mingw tools
  #     #  uses: msys2/setup-msys2@v2
  #     - name: Install dependencies
  #       uses: ./.github/actions/windows_install
  #     - name: Install python dependencies
  #       uses: ./.github/actions/pip_installation
  #     - name: Fortran/C tests with pytest
  #       uses: ./.github/actions/pytest_run
  #     - name: Python tests with pytest
  #       uses: ./.github/actions/pytest_run_python
  #     - name: Parallel tests with pytest
  #       uses: ./.github/actions/pytest_parallel

  # MacOSX:

  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python 3.10
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: '3.10'
  #     - name: Install dependencies
  #       uses: ./.github/actions/macos_install
  #     - name: Install python dependencies
  #       uses: ./.github/actions/pip_installation
  #     - name: Fortran/C tests with pytest
  #       uses: ./.github/actions/pytest_run
  #     - name: Python tests with pytest
  #       uses: ./.github/actions/pytest_run_python
  #     - name: Parallel tests with pytest
  #       uses: ./.github/actions/pytest_parallel

  # Linter:

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python 3.7
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: 3.7
  #     - name: Install python dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         python -m pip install pylint
  #       shell: bash
  #     - name: Pylint
  #       run: |
  #           python -m pylint --rcfile=.pylintrc pyccel/parser/semantic.py
  #       shell: bash
