name: Bot

on:
  pull_request_target:
    branches: [ devel ]
    types: [ ready_for_review ]

jobs:
  Bot:
    name: Preparing Pull Request for review stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/add_remote
        with:
          pr_id: ${{ github.event.number }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install python dependencies
        run: |
          python -m pip install requests
      - name: "Generate token"
        id: token
        uses: ./.github/actions/generate_bot_token
        with:
          bot_pem: "${{ secrets.BOT_PEM }}"
      - id: run_bot
        run: |
          python ci_tools/bot_ready_for_review.py
        env:
          GH_TOKEN: ${{ github.token }}

