name: Bot

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  Bot:
    name: Thanks for the Pull Request!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install python dependencies
        run: |
          python -m pip install requests jwt
      - id: run_bot
        run: |
          python ci_tools/bot_hello.py
        env:
          GH_TOKEN: ${{ github.token }}
          PEM: "${{ secrets.BOT_PEM }}"

