name: Bot

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  Bot:
    name: Thanks for the Pull Request!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: devel
          repository: ${{ github.repository }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install python dependencies
        run: |
          python -m pip install requests jwt
      - id: run_bot
        run: |
          python ci_tools/bot_hello.py
        env:
          GH_TOKEN: ${{ github.token }}
          bot_pem: "${{ secrets.BOT_PEM }}"

